# Generated by Django 5.0.7 on 2024-09-17 13:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('fecha_inicio', models.CharField(max_length=200)),
                ('fecha_fin', models.IntegerField(default=0)),
                ('tipo_permiso', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Rol', models.CharField(max_length=100)),
                ('Sede', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 17, 13, 46, 44, 941962, tzinfo=datetime.timezone.utc))),
                ('id_proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.usuario')),
            ],
        ),
    ]
