# Generated by Django 5.0.6 on 2024-10-11 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficios_tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(max_length=100)),
                ('horas_disponibles', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_permiso', models.CharField(blank=True, null=True, unique=True)),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('fecha_ingreso_empresa', models.DateField(default=django.utils.timezone.now)),
                ('campaña', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('fecha_peticion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('fecha_incorporacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo_permiso', models.CharField(max_length=80, null=True)),
                ('parentesco', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=100)),
                ('Jefe_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_permiso', models.CharField(blank=True, null=True, unique=True)),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('fecha_ingreso_empresa', models.DateField(default=django.utils.timezone.now)),
                ('campaña', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('fecha_peticion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('fecha_incorporacion', models.DateField(default=django.utils.timezone.now)),
                ('jefe', models.CharField(max_length=80, null=True)),
                ('tipo_permiso', models.CharField(max_length=80, null=True)),
                ('id_permisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.permisos')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, null=True)),
                ('codigo_tiquetera', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('campaña', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('beneficios', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('Jefe_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_vacacione', models.CharField(blank=True, unique=True)),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('fecha_ingreso_empresa', models.DateField(default=django.utils.timezone.now)),
                ('dias_vacaciones', models.CharField(max_length=5)),
                ('campaña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_peticion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_incorporacion', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.CharField(max_length=80)),
                ('periodo', models.CharField(max_length=80)),
                ('estado', models.CharField(default='Pendiente', max_length=80)),
                ('Jefe_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
