# Generated by Django 5.0.7 on 2024-09-17 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='id_proceso',
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 17, 14, 18, 57, 193184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
