# Generated by Django 5.0.7 on 2024-09-17 14:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0002_remove_historial_id_proceso_alter_historial_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(default=' ', max_length=100)),
                ('Rol', models.CharField(max_length=100)),
                ('Sede', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 17, 14, 19, 32, 440445, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='historial',
            name='id_proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.usuario'),
        ),
    ]
