# Generated by Django 5.0.7 on 2024-09-18 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0003_usuario_alter_historial_fecha_historial_id_proceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='id_proceso',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
