# Generated by Django 5.0.6 on 2024-10-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0003_rename_campaña_permisos_campana_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiquetera',
            old_name='campaña',
            new_name='campana',
        ),
    ]
