# Generated by Django 5.0.6 on 2024-10-17 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0004_rename_campaña_tiquetera_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquetera',
            name='fecha_peticion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
