# Generated by Django 5.0.6 on 2024-10-17 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0005_tiquetera_fecha_peticion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incapacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('campaña', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('turno', models.DateField()),
                ('sede', models.DateField(default=django.utils.timezone.now)),
                ('doc_incapacidad', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
