# Generated by Django 5.0.6 on 2024-10-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0006_incapacidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidades',
            name='radicado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
