# Generated by Django 5.0.7 on 2024-09-18 17:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0006_usuario_alter_historial_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='id_permisos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.permisos'),
        ),
        migrations.AddField(
            model_name='historial',
            name='id_tiquetera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.tiquetera'),
        ),
        migrations.AddField(
            model_name='historial',
            name='id_vacaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.vacaciones'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 516168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_incorporacion',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_ingreso_empresa',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tiquetera',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tiquetera',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 515174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 514175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_incorporacion',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 514175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_ingreso_empresa',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 514175, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 17, 21, 42, 514175, tzinfo=datetime.timezone.utc)),
        ),
    ]
