# Generated by Django 5.0.7 on 2024-09-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0007_historial_id_permisos_historial_id_tiquetera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='id_permisos',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id_tiquetera',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id_vacaciones',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Tiquetera',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Vacaciones',
        ),
    ]
