# Generated by Django 5.0.6 on 2024-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0007_incapacidades_radicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incapacidades',
            old_name='campaña',
            new_name='campana',
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='radicado',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
