# Generated by Django 5.0.6 on 2024-10-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0011_remove_incapacidades_radicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidades',
            name='sede',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incapacidades',
            name='turno',
            field=models.CharField(max_length=100),
        ),
    ]
