# Generated by Django 5.0.6 on 2024-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0012_alter_incapacidades_sede_alter_incapacidades_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquetera',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
