# Generated by Django 5.0.6 on 2024-10-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0013_tiquetera_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiquetera',
            name='observaciones',
            field=models.CharField(default='Hola', max_length=100),
        ),
    ]
