# Generated by Django 5.0.7 on 2024-09-18 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0014_alter_historial_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='codigo_permisos',
            field=models.CharField(default='per-00', unique=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='Codigo_vacaciones',
            field=models.CharField(default='vac-00', unique=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 2603, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 1615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 1615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_peticion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 1615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tiquetera',
            name='fecha_fin',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 1615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tiquetera',
            name='fecha_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 1615, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 18, 20, 58, 41, 559, tzinfo=datetime.timezone.utc)),
        ),
    ]
