# Generated by Django 5.0.6 on 2024-10-24 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0015_incapacidades_fecha_incorporacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidades',
            name='fecha_peticion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
