# Generated by Django 5.0.6 on 2024-10-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0017_incapacidades_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='fecha_fin',
        ),
        migrations.DeleteModel(
            name='Historial_permisos',
        ),
    ]
