# Generated by Django 5.0.6 on 2024-10-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0018_remove_permisos_fecha_fin_delete_historial_permisos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacaciones',
            old_name='Codigo_vacacione',
            new_name='Codigo_vacaciones',
        ),
    ]
