# Generated by Django 5.0.6 on 2024-10-30 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0019_rename_codigo_vacacione_vacaciones_codigo_vacaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacaciones',
            name='fecha_terminacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
