# Generated by Django 5.0.6 on 2024-10-31 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0020_vacaciones_fecha_terminacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incapacidades',
            old_name='fecha_inicio',
            new_name='fecha_inicio_incapacidad',
        ),
        migrations.AddField(
            model_name='incapacidades',
            name='fecha_terminacion_incapacidad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
