# Generated by Django 5.0.6 on 2024-09-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0026_permisos_parentesco_alter_historial_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='id_permisos',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id_tiquetera',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='id_vacaciones',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Tiquetera',
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
        migrations.DeleteModel(
            name='Vacaciones',
        ),
    ]
