# Generated by Django 5.0.6 on 2024-09-24 15:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0028_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_peticion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Historial_permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 24, 15, 44, 47, 782513, tzinfo=datetime.timezone.utc))),
                ('Estados', models.CharField(max_length=100)),
                ('id_permisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.permisos')),
            ],
        ),
        migrations.DeleteModel(
            name='Historial',
        ),
    ]
