# Generated by Django 5.0.6 on 2024-10-01 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0033_remove_permisos_observaciones_permisos_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_permisos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='campaña',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='cedula',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='fecha_incorporacion',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='fecha_peticion',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='jefe',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historial_permisos',
            name='tipo_permiso',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='Estados',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_peticion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 878360, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 874330, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 874330, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 1, 19, 49, 55, 874330, tzinfo=datetime.timezone.utc)),
        ),
    ]
