# Generated by Django 5.0.6 on 2024-10-02 13:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ausentismo', '0040_remove_tiquetera_beneficios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficios_tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio_1', models.CharField(max_length=100)),
                ('beneficio_2', models.CharField(max_length=100)),
                ('beneficio_3', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_permiso', models.CharField(blank=True, null=True, unique=True)),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_ingreso_empresa', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 738269, tzinfo=datetime.timezone.utc))),
                ('campaña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_peticion', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 738269, tzinfo=datetime.timezone.utc))),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 738269, tzinfo=datetime.timezone.utc))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 738269, tzinfo=datetime.timezone.utc))),
                ('fecha_incorporacion', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 738269, tzinfo=datetime.timezone.utc))),
                ('jefe', models.CharField(max_length=80)),
                ('tipo_permiso', models.CharField(max_length=80)),
                ('parentesco', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_vacacione', models.CharField(blank=True, unique=True)),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_ingreso_empresa', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 724169, tzinfo=datetime.timezone.utc))),
                ('dias_vacaciones', models.CharField(max_length=5)),
                ('campaña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 724169, tzinfo=datetime.timezone.utc))),
                ('fecha_fin', models.DateField()),
                ('fecha_incorporacion', models.DateField(verbose_name=datetime.datetime(2024, 10, 2, 13, 40, 2, 724169, tzinfo=datetime.timezone.utc))),
                ('observaciones', models.CharField(max_length=80)),
                ('jefe', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_permiso', models.CharField(blank=True, null=True, unique=True)),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('fecha_ingreso_empresa', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 740343, tzinfo=datetime.timezone.utc))),
                ('campaña', models.CharField(max_length=100, null=True)),
                ('cargo', models.CharField(max_length=100, null=True)),
                ('fecha_peticion', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 740343, tzinfo=datetime.timezone.utc))),
                ('fecha_inicio', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 740343, tzinfo=datetime.timezone.utc))),
                ('fecha_fin', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 740343, tzinfo=datetime.timezone.utc))),
                ('fecha_incorporacion', models.DateField(default=datetime.datetime(2024, 10, 2, 13, 40, 2, 740343, tzinfo=datetime.timezone.utc))),
                ('jefe', models.CharField(max_length=80, null=True)),
                ('tipo_permiso', models.CharField(max_length=80, null=True)),
                ('parentesco', models.CharField(max_length=100, null=True)),
                ('id_permisos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.permisos')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100)),
                ('codigo_tiquetera', models.CharField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('campaña', models.CharField(max_length=100)),
                ('jefe', models.CharField(max_length=100)),
                ('fecha_peticion', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('tipo_tiquetera', models.CharField()),
                ('beneficios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ausentismo.beneficios_tiquetera')),
            ],
        ),
    ]
