# Generated by Django 5.0.6 on 2024-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0042_remove_tiquetera_beneficios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial_permisos',
            name='id_permisos',
        ),
        migrations.DeleteModel(
            name='Tiquetera',
        ),
        migrations.DeleteModel(
            name='Vacaciones',
        ),
        migrations.DeleteModel(
            name='Historial_permisos',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
    ]
