# Generated by Django 5.0.6 on 2024-10-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0060_alter_historial_permisos_fecha_fin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='beneficios_tiquetera',
        ),
        migrations.RemoveField(
            model_name='historial_permisos',
            name='id_permisos',
        ),
        migrations.DeleteModel(
            name='Tiquetera',
        ),
        migrations.DeleteModel(
            name='Vacaciones',
        ),
        migrations.DeleteModel(
            name='Historial_permisos',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
    ]
