# Generated by Django 5.0.6 on 2024-10-07 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ausentismo', '0063_remove_permisos_jefe_remove_vacaciones_jefe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_tiquetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tiquetera', models.CharField(blank=True, max_length=100, unique=True)),
                ('cedula', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('campaña', models.CharField(max_length=100)),
                ('jefe', models.CharField(max_length=100)),
                ('fecha_peticion', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('beneficios', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('tipo_tiquetera', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Historial_vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_vacacione', models.CharField(blank=True, unique=True)),
                ('cedula', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_ingreso_empresa', models.DateField(verbose_name=datetime.datetime(2024, 10, 7, 16, 17, 4, 52936, tzinfo=datetime.timezone.utc))),
                ('dias_vacaciones', models.CharField(max_length=5)),
                ('campaña', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(verbose_name=datetime.datetime(2024, 10, 7, 16, 17, 4, 52936, tzinfo=datetime.timezone.utc))),
                ('fecha_fin', models.DateField()),
                ('fecha_incorporacion', models.DateField(verbose_name=datetime.datetime(2024, 10, 7, 16, 17, 4, 52936, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='historial_permisos',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='historial_permisos',
            name='parentesco',
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 51928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='fecha_incorporacion',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 51928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='fecha_ingreso_empresa',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 51928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 51928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historial_permisos',
            name='fecha_peticion',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 51928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 50454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_incorporacion',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 7, 16, 17, 4, 50454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_ingreso_empresa',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 50454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 50454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='fecha_peticion',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 50454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_incorporacion',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 46214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name=datetime.datetime(2024, 10, 7, 16, 17, 4, 46214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 17, 4, 46214, tzinfo=datetime.timezone.utc)),
        ),
    ]
